hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    resource_owners:
            github:
                type:                github
                client_id:           '%env(GITHUB_USERNAME)%'
                client_secret:       '%env(GITHUB_SECRET)%'
                scope:               'user:email,public_repo'
                options:
                    csrf: true

services:
    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
