security:
    providers:
        webservice:
            id: my.oauth_aware.user_provider.service

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            oauth:
                resource_owners:
                    github:          "/login/check-github"
                login_path:        /
                use_forward:       false
                failure_path:      /

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
            logout:
                path:   /logout
                target: /

            form_login:
                default_target_path: issues
                always_use_default_target_path: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_USER }